#EXTM3U
#EXT-X-VERSION:5
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="sub1",CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog,public.accessibility.describes-music-and-sound",NAME="English CC",AUTOSELECT=YES,DEFAULT=NO,FORCED=NO,LANGUAGE="en",URI="https://manifest-gcp-us-east4-vop1.cfcdn.mux.com/o5PXyOFhSSBj0202AyeLktnNu6x6JHQCNJGaf668JOsQou6lgeaJCZ20000oVrS7ulppg6XhdPzb8bI/subtitles.m3u8?cdn=fastly&expires=1693018800&signature=NjRlOTZhYjBfZGI4ZDFlNjU3YzEzNGY0NDlkOTM4OWE4ODc0NTZkOGE0NTNmYzFiMTZjZjliYTkzZjY2YzU3MDlkMGQ2MGY1YQ=="
#EXT-X-STREAM-INF:BANDWIDTH=2516370,AVERAGE-BANDWIDTH=2516370,CODECS="mp4a.40.2,avc1.640020",RESOLUTION=1280x720,CLOSED-CAPTIONS=NONE,SUBTITLES="sub1"
https://manifest-gcp-us-east4-vop1.cfcdn.mux.com/2oRyJAUawwwzj6Oj2uTUuG655vhcsF00euP02tu2hjiWIy6rZ5ArK9zshKBsW3eBIzW2y4olOQeCTTmRZceww3NMQaX6JsQlI8rmlO49TRZ4A/rendition.m3u8?cdn=fastly&expires=1693018800&rid=Ir02FmqsqUnMIpEqH89MdlvWa15QwOo6dCnelCtSI9YI&skid=default&signature=NjRlOTZhYjBfMzAwNDRjMGE4ZGRlNzc3NGQ3NTg5MTM3YjA5YTg2ODg3ZmYyNmMxZmM3MzM2MDgyYWFkNTQ3N2U1ZTE0MGUyNQ==&vsid=dT4O004rZIwC00anLuzQoTK9Jd8V46rOAswj5qAvNR00WHaiTL5nzlUAx4eza00uJrhQ2i01SM3Qv5Tw
#EXT-X-STREAM-INF:BANDWIDTH=1273366,AVERAGE-BANDWIDTH=1273366,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=854x480,CLOSED-CAPTIONS=NONE,SUBTITLES="sub1"
https://manifest-gcp-us-east4-vop1.cfcdn.mux.com/9Im8Htg92XNUVAjoGtEIZ8JfI6hhpB802s01kw0052L7a02HvktfUqAoHvZscYC01NqUlq6Ir02wUUmOMxp4P4Q1m1W0112aMlXbAefIfKzwVS9oGA/rendition.m3u8?cdn=fastly&expires=1693018800&rid=Ir02FmqsqUnMIpEqH89MdlvWa15QwOo6dCnelCtSI9YI&skid=default&signature=NjRlOTZhYjBfOTBmN2YzODFiMjQyNTZiNWUzYmI0YjdiZDBlMzE5M2U0MTQ2NTVhZjk3MWMzZWRlYTU2YTc2Y2I3NDJhZWMwYQ==&vsid=dT4O004rZIwC00anLuzQoTK9Jd8V46rOAswj5qAvNR00WHaiTL5nzlUAx4eza00uJrhQ2i01SM3Qv5Tw
#EXT-X-STREAM-INF:BANDWIDTH=4755240,AVERAGE-BANDWIDTH=4755240,CODECS="mp4a.40.2,avc1.64002a",RESOLUTION=1920x1080,CLOSED-CAPTIONS=NONE,SUBTITLES="sub1"
https://manifest-gcp-us-east4-vop1.cfcdn.mux.com/6P01101Sxgfdfp9QrWHPifQrW6CWwc00RXAAeo43bJ00FbV3BJxZnbbjrF2ZVKS6NLvsAmYsJrP01QcXdhVVyZfXdT4YrqwT4Cex02/rendition.m3u8?cdn=fastly&expires=1693018800&rid=Ir02FmqsqUnMIpEqH89MdlvWa15QwOo6dCnelCtSI9YI&skid=default&signature=NjRlOTZhYjBfNTFmMWMyZDI0YzE2OWU4MWExMDdmYmY3YzIwODM4OGEzOWIwOTkzYzM1ZTJkNzdhNmViNWM1OTMwMjExNmU2OQ==&vsid=dT4O004rZIwC00anLuzQoTK9Jd8V46rOAswj5qAvNR00WHaiTL5nzlUAx4eza00uJrhQ2i01SM3Qv5Tw
#EXT-X-STREAM-INF:BANDWIDTH=697078,AVERAGE-BANDWIDTH=697078,CODECS="mp4a.40.2,avc1.64001e",RESOLUTION=480x270,CLOSED-CAPTIONS=NONE,SUBTITLES="sub1"
https://manifest-gcp-us-east4-vop1.cfcdn.mux.com/BiGfisuE1BHPtgvM3rDLP000001IXhBu1sstPb00kD79CGRxujVYN00p1oHUEij8rajTEg00oR0201nTFSB02CTDLaROoKRHuzGqvWZTA/rendition.m3u8?cdn=fastly&expires=1693018800&rid=Ir02FmqsqUnMIpEqH89MdlvWa15QwOo6dCnelCtSI9YI&skid=default&signature=NjRlOTZhYjBfOTc2NmE2ZjEzNDQzY2JiMTNjMDIwMDA3ZGM1MTVjM2RmZmFjNjYzYjc2ZGI2NDE0MTM3ODhjYmU3MTg0ZmZjNA==&vsid=dT4O004rZIwC00anLuzQoTK9Jd8V46rOAswj5qAvNR00WHaiTL5nzlUAx4eza00uJrhQ2i01SM3Qv5Tw# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
